@startuml es2
skinparam class {
    BackgroundColor Snow
    BorderColor Black
}

Frontend -> "routes: Routes" : 1: post(/loan, req)


"routes: Routes" -> "LoanController(loanController): ILoanController" : 1.1 store(req.body): Object

"LoanController(loanController): ILoanController" -> "UserDAO : IUserDAO" : 1.1.2 user = index(req.user_id): User
"LoanController(loanController): ILoanController" <-- "UserDAO : IUserDAO" : user

"LoanController(loanController): ILoanController" -> "BookDAO : IBookDAO" : 1.1.3 book = index(req.book_id): Book
"LoanController(loanController): ILoanController" <-- "BookDAO : IBookDAO" : book


"LoanController(loanController): ILoanController" -> "loan : Loan" : 1.1.4 setUser(user): boolean
"LoanController(loanController): ILoanController" -> "loan : Loan" : 1.1.5 setBook(book): boolean
"LoanController(loanController): ILoanController" -> "loan : Loan" : 1.1.6 setStatus(req.status): boolean
"LoanController(loanController): ILoanController" -> "loan : Loan" : 1.1.7 setBorrowDate(req.borrowDate): boolean


"LoanController(loanController): ILoanController" -> "LoanDAO : ILoanDAO" : 1.1.8 res = save(loan): boolean
"LoanController(loanController): ILoanController" <-- "LoanDAO : ILoanDAO" : res

"routes: Routes" <-- "LoanController(loanController): ILoanController" : res


"routes: Routes" --> Frontend : res

@enduml
