@startuml es2
skinparam class {
    BackgroundColor Snow
    BorderColor Black
}

Frontend -> "routes: Routes" : 1: post(/loan, req)

"routes: Routes" -> "UserDAO : IUserDAO" : 1.1 user = index(req.librarian_id): User
"routes: Routes" <-- "UserDAO : IUserDAO" : user

"routes: Routes" -> "UserDAO : IUserDAO" : 1.2 librarian = index(req.user_id): User
"routes: Routes" <-- "UserDAO : IUserDAO" : librarian

"routes: Routes" -> "BookDAO : IBookDAO" : 1.3 book = index(req.book_id): Book
"routes: Routes" <-- "BookDAO : IBookDAO" : book


"routes: Routes" -> "loan : Loan" : 1.4 setUser(user): boolean
"routes: Routes" -> "loan : Loan" : 1.5 setLibrarian(librarian): boolean
"routes: Routes" -> "loan : Loan" : 1.6 setBook(book): boolean
"routes: Routes" -> "loan : Loan" : 1.7 setStatus(req.status): boolean
"routes: Routes" -> "loan : Loan" : 1.8 setBorrowDate(req.borrowDate): boolean
"routes: Routes" -> "loan : Loan" : 1.9 setBorrowReturnLimit(req.borrowReturnLimit): boolean
"routes: Routes" -> "loan : Loan" : 1.10 setReturnDate(req.returnDate): boolean


"routes: Routes" -> "LoanDAO : ILoanDAO" : 1.11 res = save(user): boolean


"routes: Routes" --> Frontend : res

@enduml
