@startuml es2
skinparam class {
    BackgroundColor Snow
    BorderColor Black
}

Frontend -> "routes: Routes" : 1: get(/loan, req)
"routes: Routes" -> "LoanController(loanController): ILoanController" : 1.1 list(req.query): Object

"LoanController(loanController): ILoanController" -> "LoanDAO : ILoanDAO" : 1.1.1 user = list(req.query): Loan[]
"LoanController(loanController): ILoanController" <-- "LoanDAO : ILoanDAO" : loanList

"LoanController(loanController): ILoanController" --> "routes: Routes" : res

"routes: Routes" --> Frontend : res

@enduml
