@startuml es2
skinparam class {
    BackgroundColor Snow
    BorderColor Black
}
Frontend -> "routes: Routes" : 1: post(/image, req)
"routes: Routes" -> "ImageController(imageController): IImageController" : 1.1 image = create(req)

"ImageController(imageController): IImageController" -> "img : Image" : 1.1.1 setWidth(req.body.name): boolean
"ImageController(imageController): IImageController" -> "img : Image" : 1.1.2 setHeight(req.body.imageType): boolean
"ImageController(imageController): IImageController" -> "img : Image" : 1.1.3 setBinaryContent(req.file): boolean

"ImageController(imageController): IImageController" -> "ImageDAO : IImageDAO" : 1.1.4 res = create(image): Object

"ImageDAO : IImageDAO" --> "ImageController(imageController): IImageController" : resImg
"routes: Routes" <-- "ImageController(imageController): IImageController" : resImg

Frontend -> "routes: Routes" : 2: post(/book, req)

"routes: Routes" -> "BookController(bookController): IBookController" : 2.1 book = create(req)


"BookController(bookController): IBookController" -> "book : Book" : 2.1.1 setImage(resImg.id)
"BookController(bookController): IBookController" -> "book : Book" : 2.1.2 setTitle(req.title): boolean
"BookController(bookController): IBookController" -> "book : Book" : 2.1.3 setAuthor(req.author): boolean
"BookController(bookController): IBookController" -> "book : Book" : 2.1.4 setYear(req.year): boolean
"BookController(bookController): IBookController" -> "book : Book" : 2.1.5 setGenres(req.genres): boolean

"BookController(bookController): IBookController" -> "BookDAO : IBookDAO" : 2.1.6 res = create(book): Object

"BookDAO : IBookDAO" --> "BookController(bookController): IBookController" : res
"routes: Routes" <-- "BookController(bookController): IBookController" : res


"routes: Routes" --> Frontend : res

@enduml
