@startuml es2
skinparam class {
    BackgroundColor Snow
    BorderColor Black
}

Frontend -> "routes: Routes" : 1: get(/book)

"routes: Routes" -> "BookController(bookController): IBookController" : 1.1 list(): Object
"BookController(bookController): IBookController" -> "bookDAO : IBookDAO" : 1.1.1 res = list(): Book[]
"BookController(bookController): IBookController" <-- "bookDAO : IBookDAO" : res

"routes: Routes" <-- "BookController(bookController): IBookController" : res

"routes: Routes" --> Frontend : res

@enduml
