@startuml es2
skinparam class {
    BackgroundColor Snow
    BorderColor Black
}

Frontend -> "routes: Routes" : 1: post(/user/login, req)

"routes: Routes" -> "UserController(userController): IUserController" : 1.1 login(req.body): Object
"UserController(userController): IUserController" -> "userDAO : IUserDAO" : 1.1.1 res = login(req.body.email, req.body.password): User
"UserController(userController): IUserController" <-- "userDAO : IUserDAO" : res

"routes: Routes" <-- "UserController(userController): IUserController" : res


"routes: Routes" --> Frontend : res

@enduml
