@startuml es2
skinparam class {
    BackgroundColor Snow
    BorderColor Black
}

Frontend -> "routes: Routes" : 1: post(/login, req)

"routes: Routes" -> "UserDao : IUserDao" : 1.1 res = login(req.email, req.password): User

"UserDao : IUserDao" --> "routes: Routes" : res

"routes: Routes" --> Frontend : res

@enduml
