@startuml es2
skinparam class {
    BackgroundColor Snow
    BorderColor Black
}

Frontend -> "routes: Routes" : 1: post(/user, req)

"routes: Routes" -> "UserController(userController): IUserController" : 1.1.1 store(req.body): Object
"UserController(userController): IUserController" -> "user : User" : 1.1.1 setName(req.body.name): boolean
"UserController(userController): IUserController" -> "user : User" : 1.1.2 setEmail(req.body.email): boolean
"UserController(userController): IUserController" -> "user : User" : 1.1.3 setPassword(req.body.password): boolean
"UserController(userController): IUserController" -> "user : User" : 1.1.4 setPhone(req.body.phone): boolean
"UserController(userController): IUserController" -> "user : User" : 1.1.5 setAddress(req.body.addres): boolean
"UserController(userController): IUserController" -> "user : User" : 1.1.6 setRole(req.body.role): boolean

"UserController(userController): IUserController" -> "userDAO : IUserDAO" : 1.1.7 res = create(user): User
"UserController(userController): IUserController" <-- "userDAO : IUserDAO" : res

"routes: Routes" <-- "UserController(userController): IUserController" : res


"routes: Routes" --> Frontend : res

@enduml
