@startuml es2
skinparam class {
    BackgroundColor Snow
    BorderColor Black
}

Frontend -> "routes: Routes" : 1: post(/register, req)

"routes: Routes" -> "user : User" : 1.1 setName(req.name): boolean
"routes: Routes" -> "user : User" : 1.2 setEmail(req.email): boolean
"routes: Routes" -> "user : User" : 1.3 setPassword(req.password): boolean
"routes: Routes" -> "user : User" : 1.4 setPhone(req.phone): boolean
"routes: Routes" -> "user : User" : 1.5 setAddress(req.addres): boolean
"routes: Routes" -> "user : User" : 1.6 setRole(NORMAL_USER): boolean

"routes: Routes" -> "UserDao : IDao" : 1.5 res = create(user): boolean

"UserDao : IDao" --> "routes: Routes" : res

"routes: Routes" --> Frontend : res

@enduml
