@startuml es2
skinparam class {
    BackgroundColor Snow
    BorderColor Black
}

Frontend -> "routes: Routes" : 1: put(/user/:id)

"routes: Routes" -> "UserController(userController): IUserController" : 1.1 update(req): Object
"UserController(userController): IUserController" -> "userDAO : IUserDAO" : 1.1.1 res = update(req.params.id, req.body): User
"UserController(userController): IUserController" <-- "userDAO : IUserDAO" : res

"routes: Routes" <-- "UserController(userController): IUserController" : res

"routes: Routes" --> Frontend : res

@enduml
